[package]
name = "server"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.9", features = ["web-axum"] }
futures = "0.3"
axum = "0.6.2"
sync_wrapper = "0.1.1"
ethers = { version = "1.0.0", features = ["abigen"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_qs = "0.11"
